import { pgTable, integer, varchar, uuid, doublePrecision, boolean, index, bigint, date, text, timestamp } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const instellingtype = pgTable("instellingtype", {
	id: integer(),
	naam: varchar({ length: 50 }),
	type: integer(),
	rowguid: uuid(),
	plaatsoverlijdenorder: integer(),
	arrestantenorder: integer(),
	schouwingorder: integer(),
	forensischorder: integer(),
	euthanasieorder: integer(),
	uitstelbegravenorder: integer(),
	letselschadeorder: integer(),
	zedendelictorder: integer(),
	overigorder: integer(),
	arrestantenorderfactuur: integer(),
	schouwingorderfactuur: integer(),
	forensischorderfactuur: integer(),
	euthanasieorderfactuur: integer(),
	uitstelbegravenorderfactuur: integer(),
	letselschadeorderfactuur: integer(),
	zedendelictorderfactuur: integer(),
	arrestantenorderplaats: integer(),
	schouwingorderplaats: integer(),
	forensischorderplaats: integer(),
	euthanasieorderplaats: integer(),
	uitstelbegravenorderplaats: integer(),
	letselschadeorderplaats: integer(),
	zedendelictorderplaats: integer(),
});

export const gesprekken = pgTable("gesprekken", {
	id: integer().primaryKey().notNull().default(sql`nextval('gesprekken_id_seq'::regclass)`),
	vannummer: varchar({ length: 20 }),
	onsnummer: varchar({ length: 20 }),
	naarnummer: varchar({ length: 20 }),
	idwaarneemgroep: integer(),
	iddeelnemer: integer(),
	van: integer(),
	tot: integer(),
	recordingFilename: varchar("recording_filename", { length: 255 }),
	telsrv: varchar({ length: 50 }),
	recordingShow: integer("recording_show"),
	wasBridged: boolean("was_bridged").default(false),
	talkDurationSec: integer("talk_duration_sec").default(0),
	dialstatus: varchar({ length: 50 })
});

export const tarieven = pgTable("tarieven", {
	id: integer(),
	idtariefregel: integer(),
	euros: doublePrecision(),
	vantijd: integer(),
	vandag: integer(),
	tottijd: integer(),
	totdag: integer(),
	pm: boolean(),
});

export const sms = pgTable("sms", {
	id: integer(),
	iddeelnemer: integer(),
	idwaarneemgroep: integer(),
	nummer: varchar({ length: 20 }),
	van: integer(),
	newid: integer(),
});

export const locaties = pgTable("locaties", {
	id: integer(),
	idinstellingtype: integer(),
	idinstelling: integer(),
	idregio: integer(),
	naam: varchar({ length: 255 }),
	zoeknaam: varchar({ length: 255 }),
	naamlang: varchar({ length: 255 }),
	adres: varchar({ length: 255 }),
	postcode: varchar({ length: 10 }),
	plaats: varchar({ length: 255 }),
	telnr: varchar({ length: 50 }),
	faxnr: varchar({ length: 50 }),
	email: varchar({ length: 255 }),
	verwijderd: integer(),
	rowguid: uuid(),
	kleur: varchar({ length: 50 }),
	afkorting: varchar({ length: 50 }),
});

export const settelnrs = pgTable("settelnrs", {
	id: integer(),
	telnr1: varchar({ length: 20 }),
	idlocatietelnr1: integer(),
	idomschrtelnr1: integer(),
	smsontvanger1: boolean(),
	telnr2: varchar({ length: 20 }),
	idlocatietelnr2: integer(),
	idomschrtelnr2: integer(),
	smsontvanger2: boolean(),
	telnr3: varchar({ length: 20 }),
	idlocatietelnr3: integer(),
	idomschrtelnr3: integer(),
	smsontvanger3: boolean(),
	telnr4: varchar({ length: 20 }),
	idlocatietelnr4: integer(),
	idomschrtelnr4: integer(),
	smsontvanger4: boolean(),
	telnr5: varchar({ length: 20 }),
	idlocatietelnr5: integer(),
	idomschrtelnr5: integer(),
	smsontvanger5: boolean(),
	rowguid: uuid(),
	laatstopgenomen: integer(),
});

export const diensten = pgTable("diensten", {
	id: integer(),
	idwaarneemgroep: integer(),
	idpraktijk: integer(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	van: bigint({ mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	tot: bigint({ mode: "number" }),
	iddeelnemer: integer(),
	rol: integer(),
	iddienstherhalen: integer(),
	idaantekening: integer(),
	iddeelnovern: integer(),
	iddienstovern: integer(),
	type: integer(),
	idshift: integer(),
	idtarief: integer(),
	idkamer: integer(),
	idtelnr: integer(),
	idlocatie: integer(),
	iddeelnemer2: integer(),
	idtaaktype: integer(),
	currDate: date("curr_date"),
	nextDate: date("next_date"),
	senderId: integer("sender_id"),
	deleteRequest: integer("delete_request"),
	status: varchar({ length: 20 }),
}, (table) => [
	index("diensten_list_idx").using("btree", table.idwaarneemgroep.asc().nullsLast().op("int4_ops"), table.van.asc().nullsLast().op("int4_ops"), table.tot.asc().nullsLast().op("int4_ops")),
]);

export const taaktypen = pgTable("taaktypen", {
	id: integer(),
	idwaarneemgroep: integer(),
	afkorting: varchar({ length: 10 }),
	omschrijving: varchar({ length: 50 }),
	minDagdelenPerWeek: integer("min_dagdelen_per_week"),
	belasting: integer(),
	idexpertise: integer(),
	iddefaultlocatie: integer(),
	idgekoppeldetaaktype: integer(),
	defaultplanningseenheid: integer(),
	verwijderd: integer(),
	kleur: varchar({ length: 50 }),
	volgorde: integer(),
	type: integer(),
	nietLocatieGebonden: boolean("niet_locatie_gebonden"),
	deelnemer2Mogelijk: boolean(),
});

export const specialismen = pgTable("specialismen", {
	id: integer(),
	omschrijving: varchar({ length: 40 }),
	bigcode: varchar({ length: 20 }),
	type: integer(),
});

export const vakantieregios = pgTable("vakantieregios", {
	id: integer(),
	naam: varchar({ length: 50 }),
});

export const rollen = pgTable("rollen", {
	id: integer(),
	idspecialisme: integer(),
	naam: varchar({ length: 255 }),
	rowguid: uuid(),
});

export const waarneemgroepdeelnemers = pgTable("waarneemgroepdeelnemers", {
	id: integer(),
	iddeelnemer: integer(),
	idwaarneemgroep: integer(),
	idgroep: integer(),
	aangemeld: boolean(),
	fte: doublePrecision(),
	fteDd: varchar("fte_dd", { length: 50 }),
	perDd: varchar("per_dd", { length: 50 }),
	ftePp: varchar("fte_pp", { length: 50 }),
	perPp: varchar("per_pp", { length: 50 }),
	dokterdienst: varchar({ length: 50 }),
	dokterdienstEntryDate: varchar("dokterdienst_entry_date", { length: 50 }),
	dokterdienstStopDate: varchar("dokterdienst_stop_date", { length: 50 }),
	practiceScheduler: varchar("practice_scheduler", { length: 50 }),
	practiceSchedulerEntryDate: varchar("practice_scheduler_entry_date", { length: 50 }),
	practiceSchedulerStopDate: varchar("practice_scheduler_stop_date", { length: 50 }),
	idfunctie: integer(),
});

export const instellingen = pgTable("instellingen", {
	id: integer(),
	idinstellingtype: integer(),
	naam: varchar({ length: 50 }),
	naamlang: varchar({ length: 255 }),
	url: varchar({ length: 40 }),
	telnr: varchar({ length: 20 }),
	idhoofdlocatie: integer(),
	rowguid: uuid(),
});

export const vakanties = pgTable("vakanties", {
	id: integer(),
	idvakantieregio: integer(),
	naam: varchar({ length: 255 }),
	van: integer(),
	tot: integer(),
	type: integer(),
});

export const account = pgTable("account", {
	id: text().primaryKey().notNull(),
	accountId: text().notNull(),
	providerId: text().notNull(),
	userId: text().notNull(),
	accessToken: text(),
	refreshToken: text(),
	idToken: text(),
	accessTokenExpiresAt: timestamp({ withTimezone: true, mode: 'string' }),
	refreshTokenExpiresAt: timestamp({ withTimezone: true, mode: 'string' }),
	scope: text(),
	password: text(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
});

export const authVerification = pgTable("auth_verification", {
	id: text().notNull(),
	identifier: text().notNull(),
	value: text().notNull(),
	expiresAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
});

export const session = pgTable("session", {
	id: text().notNull(),
	expiresAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	token: text().notNull(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	ipAddress: text(),
	userAgent: text(),
	userId: text().notNull(),
});

export const deelnemers = pgTable("deelnemers", {
	id: integer(),
	idgroep: integer(),
	achternaam: varchar({ length: 50 }),
	voorletterstussenvoegsel: varchar({ length: 50 }),
	voornaam: varchar({ length: 50 }),
	name: varchar({ length: 50 }),
	initialen: varchar({ length: 50 }),
	geslacht: boolean(),
	afwijkendefunctie: varchar({ length: 50 }),
	color: varchar({ length: 50 }),
	afgemeld: boolean(),
	idlocatie: integer(),
	idspecialisme: integer(),
	idpraktijk: integer(),
	idwaarneemgroep: integer(),
	idlocatienu: integer(),
	huisadrstraatnr: varchar({ length: 50 }),
	huisadrpostcode: varchar({ length: 50 }),
	huisadrplaats: varchar({ length: 50 }),
	huisadrtelnr: varchar({ length: 50 }),
	huisadrfax: varchar({ length: 50 }),
	huisemail: varchar({ length: 50 }),
	login: varchar({ length: 50 }),
	smscode: varchar({ length: 10 }),
	smstime: integer(),
	ip: varchar({ length: 50 }),
	lastactiontime: integer(),
	idrol: integer(),
	abonnementdd: boolean(),
	aboforensys: boolean(),
	abocalamiteiten: boolean(),
	abooutsync: boolean(),
	idsettelnrdienst: integer(),
	followmetelnr: varchar({ length: 50 }),
	idovergenomendoor: integer(),
	overgenomenvanaf: integer(),
	overgenomentot: integer(),
	reminderpermin: integer(),
	dagbegin: integer(),
	dageind: integer(),
	tarief: integer(),
	roosterpersoonlijk: boolean(),
	dddienstzien: boolean(),
	ddzien: boolean(),
	bezzien: boolean(),
	shiftzien: boolean(),
	vkzien: boolean(),
	przien: boolean(),
	vakzien: boolean(),
	allewgzien: boolean(),
	uitgebreidzoeken: boolean(),
	echtedeelnemer: boolean(),
	printlijst: boolean(),
	printlijstae: boolean(),
	laatstevoorkeur: boolean(),
	outlook: boolean(),
	outlookemail: varchar({ length: 50 }),
	outlookdate: varchar({ length: 30 }),
	rowguid: uuid(),
	smsdienstbegin: boolean(),
	eigentelwelkomwav: boolean(),
	gespreksopname: boolean(),
	subtakenzien: boolean(),
	spreekurenzien: boolean(),
	fellow: boolean(),
	isVoicemailDoorschakeling: boolean("is_voicemail_doorschakeling"),
	encryptedPassword: varchar("encrypted_password", { length: 32 }),
	password: varchar({ length: 255 }),
	email: varchar({ length: 50 }),
	willBeScheduled: boolean("will_be_scheduled"),
	callRecording: boolean("call_recording"),
	ownObservationMessage: boolean("own_observation_message"),
	mijnExpertises: varchar("mijn_expertises", { length: 500 }),
	isForgotPassword: varchar("is_forgot_password", { length: 500 }),
	emailVerified: boolean("email_verified"),
	image: varchar({ length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	role: varchar({ length: 50 }),
});

export const groepen = pgTable("groepen", {
	id: integer(),
	naam: varchar({ length: 30 }),
	deelnemertoev: boolean(),
	deelnemerwijz: boolean(),
	deelnemerverw: boolean(),
	deelnemerlocatienuwijz: boolean(),
	waarneemgroeptoev: boolean(),
	waarneemgroepwijz: boolean(),
	waarneemgroepverw: boolean(),
	specialismen: boolean(),
	regios: boolean(),
	artsen: boolean(),
	instellingen: boolean(),
	locaties: boolean(),
	omschrijvingtelnrstoev: boolean(),
	omschrijvingtelnrswijz: boolean(),
	omschrijvingtelnrsverw: boolean(),
	settelnrstoev: boolean(),
	settelnrswijz: boolean(),
	settelnrsverw: boolean(),
	dienst: boolean(),
	diensttoev: boolean(),
	dienstwijz: boolean(),
	dienstverw: boolean(),
	dienstruil: boolean(),
	dienstalleeneigen: boolean(),
	dienstbinnenwg: boolean(),
	shift: boolean(),
	voorkeur: boolean(),
	groeptoev: boolean(),
	groepwijz: boolean(),
	groepverw: boolean(),
	telefoonovernemen: boolean(),
	tarieven: boolean(),
	facturering: boolean(),
	vakanties: boolean(),
	calamiteiten: boolean(),
	maatschapplanner: boolean(),
});

export const dienstherhalen = pgTable("dienstherhalen", {
	id: integer(),
	weken: integer(),
	startdatum: integer(),
	einddatum: integer(),
});

export const dienstaantekening = pgTable("dienstaantekening", {
	id: integer(),
	tekst: varchar({ length: 25 }),
	afwezig: boolean(),
	iddeelnemer: integer(),
	idwaarneemgroep: integer(),
	verwijderd: boolean(),
	prio: integer(),
	idtariefDefault: integer("idtarief_default"),
});

export const regios = pgTable("regios", {
	id: integer(),
	naam: varchar({ length: 40 }),
	rowguid: uuid(),
});

export const waarneemgroepen = pgTable("waarneemgroepen", {
	id: integer(),
	naam: varchar({ length: 50 }),
	idspecialisme: integer(),
	idregio: integer(),
	idinstelling: integer(),
	idlocatie: integer(),
	telnringaand: varchar({ length: 50 }),
	telnrnietopgenomen: varchar({ length: 50 }),
	telnronzecentrale: varchar({ length: 50 }),
	telnronzecentrale2: varchar({ length: 50 }),
	telnrconference: varchar({ length: 50 }),
	idfacturering: integer(),
	iddeelnemersecr: integer(),
	urentellingvan: integer(),
	urentellingtot: integer(),
	idinvoegendewaarneemgroep: integer(),
	regiobeschrijving: varchar({ length: 1024 }),
	veldfilters: integer(),
	veldfilterssecr: integer(),
	afgemeld: boolean(),
	recordabo: boolean(),
	ccemail: varchar({ length: 50 }),
	email: varchar({ length: 50 }),
	smsdienstbegin: boolean(),
	idliason1: integer(),
	idliason2: integer(),
	idliason3: integer(),
	idliason4: integer(),
	idcoordinatorwaarneemgroep: integer(),
	crisispinliason: varchar({ length: 50 }),
	crisispindeelnemer: varchar({ length: 50 }),
	crisispintime: integer(),
	eigentelwelkomwav: boolean(),
	abomaatschapplanner: boolean(),
	gebruiktVoicemail: boolean("gebruikt_voicemail"),
	gespreksopname: integer(),
	eigentelwelkomlocatie: varchar({ length: 512 }),
	abbonementDoktersdienst: boolean("abbonement_doktersdienst"),
	laatstAangemeldDoktersdienst: timestamp("laatst_aangemeld_doktersdienst", { mode: 'string' }),
	laastsAfgemeldDoktersidenst: timestamp("laasts_afgemeld_doktersidenst", { mode: 'string' }),
});
